version: "3.5"
services:
  core-des-container:
    container_name: ${artifactId}
    image: ${artifactId}-app:1
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
       - /data/${artifactId}-app
    ports:
      - "8080:8080"